const siteSettings={name:'siteSettings',title:'Site Settings',type:'document',fields:[{name:'brandName',type:'string'},{name:'tagline',type:'string'},{name:'email',type:'string'},{name:'phone',type:'string'},{name:'location',type:'string'},{name:'logo',type:'image',options:{hotspot:true}},{name:'navigation',type:'array',of:[{type:'object',fields:[{name:'label',type:'string'},{name:'href',type:'string'}]}]},{name:'footerText',type:'text'}]};

const page={name:'page',title:'Pages',type:'document',fields:[{name:'title',type:'string'},{name:'slug',type:'slug',options:{source:'title'}},{name:'seoTitle',type:'string'},{name:'seoDescription',type:'text'},{name:'sections',type:'array',of:[{type:'object',fields:[{name:'sectionType',type:'string',options:{list:['hero','text','gallery','products','video','cta']}},{name:'heading',type:'string'},{name:'subheading',type:'string'},{name:'body',type:'text'},{name:'image',type:'image',options:{hotspot:true}},{name:'videoUrl',type:'url'},{name:'visible',type:'boolean',initialValue:true}]}]}]};

const category={name:'category',title:'Categories',type:'document',fields:[{name:'name',type:'string'},{name:'slug',type:'slug',options:{source:'name'}},{name:'description',type:'text'},{name:'image',type:'image',options:{hotspot:true}},{name:'parent',type:'reference',to:[{type:'category'}]},{name:'order',type:'number'},{name:'visible',type:'boolean',initialValue:true}]};

const filterGroup={name:'filterGroup',title:'Catalogue Filters',type:'document',fields:[{name:'label',type:'string'},{name:'key',type:'string'},{name:'options',type:'array',of:[{type:'string'}]},{name:'order',type:'number'},{name:'openByDefault',type:'boolean'},{name:'visible',type:'boolean',initialValue:true}]};

const product={name:'product',title:'Products',type:'document',fields:[{name:'name',type:'string'},{name:'slug',type:'slug',options:{source:'name'}},{name:'description',type:'text'},{name:'images',type:'array',of:[{type:'image',options:{hotspot:true}}]},{name:'videoUrl',type:'url'},{name:'category',type:'reference',to:[{type:'category'}]},{name:'collection',type:'string'},{name:'gemstone',type:'string'},{name:'colour',type:'string'},{name:'shape',type:'string'},{name:'origin',type:'string'},{name:'metal',type:'string'},{name:'carat',type:'number'},{name:'price',type:'number'},{name:'priceOnRequest',type:'boolean',initialValue:true},{name:'availability',type:'string',options:{list:['Available','Reserved','Sold']}},{name:'featured',type:'boolean'},{name:'offerLabel',type:'string'},{name:'certification',type:'string'},{name:'seoTitle',type:'string'},{name:'seoDescription',type:'text'}]};

export const schemaTypes=[siteSettings,page,category,filterGroup,product];
